#!/usr/bin/env bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

echo ""
echo -e "${BOLD}  ╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}  ║       ${CYAN}Computerzentrale Setup${NC}${BOLD}          ║${NC}"
echo -e "${BOLD}  ╚═══════════════════════════════════════╝${NC}"
echo ""

# Detect project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env"
BACKEND_ENV_FILE="$PROJECT_ROOT/backend/.env"

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
  echo -e "${YELLOW}⚠ .env file already exists at:${NC} $ENV_FILE"
  read -p "  Overwrite? (y/N) " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${DIM}  Setup cancelled.${NC}"
    exit 0
  fi
fi

echo -e "${BLUE}Generating secrets...${NC}"
echo ""

# Generate secrets
ENCRYPTION_SECRET=$(openssl rand -hex 32)
INFLUXDB_TOKEN=$(openssl rand -hex 32)
INFLUXDB_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)

# Ask for app password
echo -e "${BOLD}App Password${NC} ${DIM}(protects the web interface)${NC}"
echo -e "${DIM}  Leave empty to disable password protection.${NC}"
read -p "  Password: " -s APP_PASSWORD_INPUT
echo ""
echo ""

# Ask for InfluxDB setup
echo -e "${BOLD}InfluxDB${NC} ${DIM}(required for metrics history and charts)${NC}"
echo -e "${DIM}  Default: http://localhost:8086 (Docker) or leave empty to disable.${NC}"
read -p "  InfluxDB URL [http://localhost:8086]: " INFLUXDB_URL_INPUT
INFLUXDB_URL="${INFLUXDB_URL_INPUT:-http://localhost:8086}"
echo ""

# Write root .env
cat > "$ENV_FILE" << EOF
# ============================================
# Computerzentrale Environment Configuration
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# ============================================

# Encryption secret — used for SSH key encryption and JWT tokens
# CRITICAL: Do not change after initial setup (encrypted data becomes unreadable)
ENCRYPTION_SECRET=$ENCRYPTION_SECRET

# App password — protects the web interface (leave empty to disable)
APP_PASSWORD=${APP_PASSWORD_INPUT:-}

# InfluxDB — time-series database for metrics history
INFLUXDB_URL=$INFLUXDB_URL
INFLUXDB_TOKEN=$INFLUXDB_TOKEN
INFLUXDB_ORG=computerzentrale
INFLUXDB_BUCKET=ping_metrics
INFLUXDB_ADMIN_PASSWORD=$INFLUXDB_ADMIN_PASSWORD

# Server port (default: 3001)
# PORT=3001

# Server metrics collection interval in seconds (default: 10)
# SERVER_METRICS_INTERVAL=10
EOF

# Write backend .env (for local development without Docker)
cat > "$BACKEND_ENV_FILE" << EOF
# Backend environment (for local development)
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

PORT=3001
NODE_ENV=development
DATABASE_PATH=./data/computerzentrale.db

ENCRYPTION_SECRET=$ENCRYPTION_SECRET
APP_PASSWORD=${APP_PASSWORD_INPUT:-}

INFLUXDB_URL=$INFLUXDB_URL
INFLUXDB_TOKEN=$INFLUXDB_TOKEN
INFLUXDB_ORG=computerzentrale
INFLUXDB_BUCKET=ping_metrics

REDIS_URL=redis://localhost:6379

SERVER_METRICS_INTERVAL=10
EOF

echo -e "${GREEN}✓ Environment files created${NC}"
echo ""
echo -e "  ${DIM}Root:${NC}    $ENV_FILE"
echo -e "  ${DIM}Backend:${NC} $BACKEND_ENV_FILE"
echo ""

# Summary
echo -e "${BOLD}  ┌─────────────────────────────────────┐${NC}"
echo -e "${BOLD}  │           ${GREEN}Setup Complete${NC}${BOLD}             │${NC}"
echo -e "${BOLD}  └─────────────────────────────────────┘${NC}"
echo ""
echo -e "  ${DIM}Encryption:${NC}  ${GREEN}✓${NC} Random 256-bit key generated"
if [ -n "${APP_PASSWORD_INPUT:-}" ]; then
  echo -e "  ${DIM}Password:${NC}    ${GREEN}✓${NC} Web interface protected"
else
  echo -e "  ${DIM}Password:${NC}    ${YELLOW}○${NC} Disabled (open access)"
fi
echo -e "  ${DIM}InfluxDB:${NC}    ${GREEN}✓${NC} Token and admin password generated"
echo ""
echo -e "  ${BOLD}Next steps:${NC}"
echo ""
echo -e "  ${CYAN}Docker:${NC}"
echo -e "    docker compose up -d"
echo ""
echo -e "  ${CYAN}Local development:${NC}"
echo -e "    npm install"
echo -e "    npm run dev"
echo ""
